// Generated by tools/calibration_profile.py presets from calibrations/*.json.
// Do not edit; change the profiles and regenerate.
#ifndef ACIDUS_CALIBRATION_PRESETS_HPP
#define ACIDUS_CALIBRATION_PRESETS_HPP

#include "SynthEngine.hpp"

namespace acidus {

struct CalibrationPreset {
    const char* id;     // profile name (calibrations/<id>.json)
    const char* name;   // shown on the logo plate
    SynthParameters params;   // every calibration constant set; front-panel fields at their defaults
};

constexpr int kCalibrationPresetCount = 4;

inline SynthParameters makeCalibrationPreset_x0x() {
    SynthParameters p;
    p.oscCouplingHz = 47.2397f;
    p.resCouplingHz = 104.291f;
    p.filterFeedbackGain = 19.2915f;
    p.filterPostHpHz = 198.892f;
    p.filterNotchHz = 7.5164f;
    p.filterNotchBandwidthHz = 4.7f;
    p.filterAllpassHz = 14.008f;
    p.filterInputCouplingHz = 6.01647f;
    p.filterOutputCouplingHz = 20000.0f;
    p.filterCapScale1 = 1.28949f;
    p.filterCapScale2 = 0.697635f;
    p.filterCapScale3 = 0.912745f;
    p.filterCapScale4 = 1.06305f;
    p.filterLadderInputScale = 0.0352243f;
    p.filterLadderTopology = 0.0f;
    p.vegDecaySec = 2.68385f;
    p.vcaGateOffMs = 0.811348f;
    p.vcaGateOffAccentMs = 2.80367f;
    p.vcaResTapRatio = 1.24556f;
    p.vcaGainSaturationDrive = 0.0f;
    p.vcoOctaveScale = 1.0f;
    p.cutoffBaseHz = 184.076f;
    p.cutoffSpanOct = 3.09108f;
    p.cutoffMaxHz = 23723.3f;
    p.cutoffTaperExp = 1.42889f;
    p.envModScaleC0 = 0.761449f;
    p.envModScaleC0Slope = 3.9723f;
    p.envModScaleC1 = 0.777939f;
    p.envModScaleC1Slope = 4.53338f;
    p.envModOffset = 0.334723f;
    p.envModTaperExp = 2.0f;
    p.envModTaperMid = 0.686116f;
    p.envModTaperWidth = 0.121931f;
    p.envModOffsetCutSlope = -0.0238615f;
    p.accentSweepDepthOct = 8.60691f;
    p.accentVcaDepth = 1.62417f;
    p.accentChargeBaseSec = 0.0305791f;
    p.accentChargePotSec = 0.0440208f;
    p.accentDiodeDrop = 0.300332f;
    p.accentMixSec = 0.144977f;
    p.oscSawLpfHz = 40000.0f;
    p.oscSawShape = 0.0f;
    p.oscSquareDutyDepth = 0.12f;
    p.oscSquareLevel = 0.598235f;
    p.vcfAttackMs = 0.1f;
    p.vcaNormalDelayMs = 4.50396f;
    p.vcaAttackMs = 1.30112f;
    p.vcfDecayMinSec = 0.0654089f;
    p.vcfDecayMaxSec = 0.984139f;
    p.vcfDecayTaper = 17.9825f;
    p.accentDecaySec = 0.0726633f;
    p.filterResonanceSkew = -0.871804f;
    p.filterResonanceLimit = 0.999842f;
    return p;
}

inline SynthParameters makeCalibrationPreset_acidvoice() {
    SynthParameters p;
    p.oscCouplingHz = 55.2836f;
    p.resCouplingHz = 104.291f;
    p.filterFeedbackGain = 17.9409f;
    p.filterPostHpHz = 188.838f;
    p.filterNotchHz = 7.5164f;
    p.filterNotchBandwidthHz = 4.7f;
    p.filterAllpassHz = 14.008f;
    p.filterInputCouplingHz = 6.01647f;
    p.filterOutputCouplingHz = 20000.0f;
    p.filterCapScale1 = 1.28949f;
    p.filterCapScale2 = 0.697635f;
    p.filterCapScale3 = 0.912745f;
    p.filterCapScale4 = 1.06305f;
    p.filterLadderInputScale = 0.0352243f;
    p.filterLadderTopology = 0.0f;
    p.vegDecaySec = 1.90844f;
    p.vcaGateOffMs = 0.811348f;
    p.vcaGateOffAccentMs = 2.80367f;
    p.vcaResTapRatio = 1.95821f;
    p.vcaGainSaturationDrive = 0.0f;
    p.vcoOctaveScale = 1.0f;
    p.cutoffBaseHz = 219.775f;
    p.cutoffSpanOct = 3.19598f;
    p.cutoffMaxHz = 23723.3f;
    p.cutoffTaperExp = 2.26027f;
    p.envModScaleC0 = 0.927279f;
    p.envModScaleC0Slope = 3.9723f;
    p.envModScaleC1 = 0.881308f;
    p.envModScaleC1Slope = 4.53338f;
    p.envModOffset = 0.177802f;
    p.envModTaperExp = 2.0f;
    p.envModTaperMid = 0.686116f;
    p.envModTaperWidth = 0.121931f;
    p.envModOffsetCutSlope = -0.0238615f;
    p.accentSweepDepthOct = 7.93757f;
    p.accentVcaDepth = 2.28956f;
    p.accentChargeBaseSec = 0.0305791f;
    p.accentChargePotSec = 0.0440208f;
    p.accentDiodeDrop = 0.300332f;
    p.accentMixSec = 0.144977f;
    p.oscSawLpfHz = 40000.0f;
    p.oscSawShape = 0.0f;
    p.oscSquareDutyDepth = 0.12f;
    p.oscSquareLevel = 0.598235f;
    p.vcfAttackMs = 0.1f;
    p.vcaNormalDelayMs = 4.50396f;
    p.vcaAttackMs = 1.30112f;
    p.vcfDecayMinSec = 0.0654089f;
    p.vcfDecayMaxSec = 0.984139f;
    p.vcfDecayTaper = 17.9825f;
    p.accentDecaySec = 0.0726633f;
    p.filterResonanceSkew = -0.871804f;
    p.filterResonanceLimit = 0.964389f;
    return p;
}

inline SynthParameters makeCalibrationPreset_factory() {
    SynthParameters p;
    p.oscCouplingHz = 47.2397f;
    p.resCouplingHz = 104.291f;
    p.filterFeedbackGain = 19.2915f;
    p.filterPostHpHz = 198.892f;
    p.filterNotchHz = 7.5164f;
    p.filterNotchBandwidthHz = 4.7f;
    p.filterAllpassHz = 14.008f;
    p.filterInputCouplingHz = 6.01647f;
    p.filterOutputCouplingHz = 20000.0f;
    p.filterCapScale1 = 1.28949f;
    p.filterCapScale2 = 0.697635f;
    p.filterCapScale3 = 0.912745f;
    p.filterCapScale4 = 1.06305f;
    p.filterLadderInputScale = 0.0352243f;
    p.filterLadderTopology = 0.0f;
    p.vegDecaySec = 1.5f;
    p.vcaGateOffMs = 0.811348f;
    p.vcaGateOffAccentMs = 2.80367f;
    p.vcaResTapRatio = 1.24556f;
    p.vcaGainSaturationDrive = 0.0f;
    p.vcoOctaveScale = 1.0f;
    p.cutoffBaseHz = 273.55f;
    p.cutoffSpanOct = 3.09108f;
    p.cutoffMaxHz = 23723.3f;
    p.cutoffTaperExp = 1.42889f;
    p.envModScaleC0 = 0.761449f;
    p.envModScaleC0Slope = 3.9723f;
    p.envModScaleC1 = 0.777939f;
    p.envModScaleC1Slope = 4.53338f;
    p.envModOffset = 0.334723f;
    p.envModTaperExp = 2.0f;
    p.envModTaperMid = 0.686116f;
    p.envModTaperWidth = 0.121931f;
    p.envModOffsetCutSlope = -0.0238615f;
    p.accentSweepDepthOct = 8.60691f;
    p.accentVcaDepth = 1.62417f;
    p.accentChargeBaseSec = 0.047f;
    p.accentChargePotSec = 0.05f;
    p.accentDiodeDrop = 0.300332f;
    p.accentMixSec = 0.1f;
    p.oscSawLpfHz = 40000.0f;
    p.oscSawShape = 0.0f;
    p.oscSquareDutyDepth = 0.12f;
    p.oscSquareLevel = 0.598235f;
    p.vcfAttackMs = 0.1f;
    p.vcaNormalDelayMs = 4.50396f;
    p.vcaAttackMs = 1.30112f;
    p.vcfDecayMinSec = 0.068f;
    p.vcfDecayMaxSec = 1.068f;
    p.vcfDecayTaper = 17.9825f;
    p.accentDecaySec = 0.068f;
    p.filterResonanceSkew = -0.871804f;
    p.filterResonanceLimit = 0.999842f;
    return p;
}

inline SynthParameters makeCalibrationPreset_hellfish() {
    SynthParameters p;
    p.oscCouplingHz = 47.2397f;
    p.resCouplingHz = 104.291f;
    p.filterFeedbackGain = 19.2915f;
    p.filterPostHpHz = 198.892f;
    p.filterNotchHz = 7.5164f;
    p.filterNotchBandwidthHz = 4.7f;
    p.filterAllpassHz = 14.008f;
    p.filterInputCouplingHz = 6.01647f;
    p.filterOutputCouplingHz = 20000.0f;
    p.filterCapScale1 = 1.28949f;
    p.filterCapScale2 = 0.697635f;
    p.filterCapScale3 = 0.912745f;
    p.filterCapScale4 = 1.06305f;
    p.filterLadderInputScale = 0.07045f;
    p.filterLadderTopology = 0.0f;
    p.vegDecaySec = 1.5f;
    p.vcaGateOffMs = 0.811348f;
    p.vcaGateOffAccentMs = 2.80367f;
    p.vcaResTapRatio = 1.24556f;
    p.vcaGainSaturationDrive = 0.0f;
    p.vcoOctaveScale = 1.0f;
    p.cutoffBaseHz = 273.55f;
    p.cutoffSpanOct = 3.09108f;
    p.cutoffMaxHz = 23723.3f;
    p.cutoffTaperExp = 1.42889f;
    p.envModScaleC0 = 0.761449f;
    p.envModScaleC0Slope = 3.9723f;
    p.envModScaleC1 = 0.777939f;
    p.envModScaleC1Slope = 4.53338f;
    p.envModOffset = 0.334723f;
    p.envModTaperExp = 2.0f;
    p.envModTaperMid = 0.686116f;
    p.envModTaperWidth = 0.121931f;
    p.envModOffsetCutSlope = -0.0238615f;
    p.accentSweepDepthOct = 8.60691f;
    p.accentVcaDepth = 1.62417f;
    p.accentChargeBaseSec = 0.047f;
    p.accentChargePotSec = 0.05f;
    p.accentDiodeDrop = 0.300332f;
    p.accentMixSec = 0.1f;
    p.oscSawLpfHz = 40000.0f;
    p.oscSawShape = 0.0f;
    p.oscSquareDutyDepth = 0.12f;
    p.oscSquareLevel = 0.598235f;
    p.vcfAttackMs = 0.1f;
    p.vcaNormalDelayMs = 4.50396f;
    p.vcaAttackMs = 3.0f;
    p.vcfDecayMinSec = 0.03f;
    p.vcfDecayMaxSec = 3.0f;
    p.vcfDecayTaper = 17.9825f;
    p.accentDecaySec = 0.2f;
    p.filterResonanceSkew = -0.871804f;
    p.filterResonanceLimit = 0.999842f;
    return p;
}

inline const CalibrationPreset* calibrationPresets() {
    static const CalibrationPreset presets[kCalibrationPresetCount] = {
        {"x0x", "X0X", makeCalibrationPreset_x0x()},
        {"acidvoice", "ACIDVOICE", makeCalibrationPreset_acidvoice()},
        {"factory", "FACTORY", makeCalibrationPreset_factory()},
        {"hellfish", "HELL FISH", makeCalibrationPreset_hellfish()},
    };
    return presets;
}

} // namespace acidus

#endif // ACIDUS_CALIBRATION_PRESETS_HPP
