#!/usr/bin/env python3
"""Rasterize the modern GUI skin's label font into a C++ header.

The modern skin (ACIDUS_GUI_STYLE=MODERN) prints its panel labels in an
anti-aliased Helvetica-like face, as on the TB-303's silk-screened panel.
Rather than ship a font file and a TrueType rasterizer, this script renders
the few glyphs the panel needs (space..Z) once, offline, into 4-bit alpha
bitmaps at the GUI's 2x supersampled resolution, slightly condensed like the
303's lettering. Re-run it only to change the face or size:

    python3 tools/gen_label_font.py [path/to/LiberationSans-Bold.ttf]

Writes src/gui/modern/LabelFontData.hpp. Needs Pillow.
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

FONT = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
PX = 20            # font size in supersampled (2x) pixels
CONDENSE = 0.86    # horizontal squeeze, like the 303's narrow lettering
OVERSAMPLE = 4     # render bigger, then box-filter down for clean edges
FIRST, LAST = 32, 90

out = Path(__file__).resolve().parent.parent / "src/gui/modern/LabelFontData.hpp"
font = ImageFont.truetype(FONT, PX * OVERSAMPLE)
ascent, descent = font.getmetrics()
ascent = (ascent + OVERSAMPLE - 1) // OVERSAMPLE
cap = font.getbbox("H")
cap_h = round((cap[3] - cap[1]) / OVERSAMPLE)
cap_top = round(cap[1] / OVERSAMPLE)

glyphs, data = [], []
for code in range(FIRST, LAST + 1):
    ch = chr(code)
    adv = font.getlength(ch) * CONDENSE / OVERSAMPLE
    bbox = font.getbbox(ch)
    if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
        glyphs.append((len(data), 0, 0, 0, 0, round(adv * 16)))
        continue
    # Pad the box to the oversample grid so the downsample stays aligned.
    x0 = (bbox[0] // OVERSAMPLE) * OVERSAMPLE
    y0 = (bbox[1] // OVERSAMPLE) * OVERSAMPLE
    W = bbox[2] - x0
    H = bbox[3] - y0
    img = Image.new("L", (W + OVERSAMPLE, H + OVERSAMPLE), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)
    w = max(1, round(img.width * CONDENSE / OVERSAMPLE))
    h = max(1, img.height // OVERSAMPLE)
    small = img.resize((w, h), Image.BOX)
    # Trim empty columns/rows the padding added.
    bb = small.getbbox()
    if bb is None:
        glyphs.append((len(data), 0, 0, 0, 0, round(adv * 16)))
        continue
    small = small.crop(bb)
    off_x = round(x0 * CONDENSE / OVERSAMPLE) + bb[0]
    off_y = y0 // OVERSAMPLE + bb[1]
    px = list(small.tobytes())
    nib = [min(15, (v + 8) // 17) for v in px]
    if len(nib) % 2:
        nib.append(0)
    start = len(data)
    data += [(nib[i] << 4) | nib[i + 1] for i in range(0, len(nib), 2)]
    glyphs.append((start, small.width, small.height, off_x, off_y, round(adv * 16)))

lines = [
    "// Generated by tools/gen_label_font.py -- do not edit.",
    "// Glyphs rasterized from Liberation Sans Bold, Copyright (c) 2012 Red Hat,",
    "// Inc., with Reserved Font Name Liberation; digitized data (c) 2010 Google",
    "// Corporation. Licensed under the SIL Open Font License 1.1",
    "// (https://openfontlicense.org).",
    "#ifndef ACIDUS_LABEL_FONT_DATA_HPP",
    "#define ACIDUS_LABEL_FONT_DATA_HPP",
    "",
    "#include <cstdint>",
    "",
    "namespace acidus {",
    "namespace labelfont {",
    "",
    f"constexpr int kFirst = {FIRST};",
    f"constexpr int kLast = {LAST};",
    f"constexpr int kAscent = {ascent};   // top of the line box to the baseline",
    f"constexpr int kCapHeight = {cap_h};",
    f"constexpr int kCapTop = {cap_top};    // top of the line box to the top of a capital",
    "",
    "// Glyph: offset into kAlpha, bitmap size, bitmap offset from the pen",
    "// position at the top of the line box, and advance in 1/16 pixels.",
    "struct Glyph { uint16_t offset; uint8_t w, h; int8_t dx, dy; uint16_t advance16; };",
    "",
    "constexpr Glyph kGlyphs[] = {",
]
for code, g in zip(range(FIRST, LAST + 1), glyphs):
    c = chr(code)
    cmt = c if c not in "\\" else "backslash"
    lines.append(f"    {{{g[0]}, {g[1]}, {g[2]}, {g[3]}, {g[4]}, {g[5]}}},  // '{cmt}'")
lines += ["};", "", "// 4-bit alpha, two pixels per byte, high nibble first, rows packed.",
          "constexpr uint8_t kAlpha[] = {"]
for i in range(0, len(data), 20):
    lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 20]) + ",")
lines += ["};", "", "} // namespace labelfont", "} // namespace acidus", "",
          "#endif // ACIDUS_LABEL_FONT_DATA_HPP", ""]
out.write_text("\n".join(lines))
print(f"wrote {out}: {len(glyphs)} glyphs, {len(data)} bytes, cap height {cap_h}")
